version: '3'
services:
  spring-green:
    image: backend
    build: ./backend
    expose:
      - ${GREEN_BACKEND_PORT}
    container_name: ${GREEN_BACKEND_NAME}

  react-green:
    image: frontend
    build: ./frontend
    depends_on:
      - spring-green
    expose:
      - ${GREEN_FRONTEND_PORT}
    environment:
       - WDS_SOCKET_HOST=0.0.0.0
       - WDS_SOCKET_PORT=0
    container_name: ${GREEN_FRONTEND_NAME}